# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ROCrYUiyCCcM972aeUtetTd9YsGxht9g
"""

import streamlit as st
import matplotlib.pyplot as plt
import matplotlib.patches as patches

def narysuj_mikolaja_z_workiem():
    # Ustawienie rozmiaru wykresu i tła
    # Używamy fig, ax = plt.subplots(), aby uzyskać obiekt figury
    fig, ax = plt.subplots(figsize=(8, 10))

    # Ustawiamy limity od 0 do 10, aby łatwo było pozycjonować elementy
    ax.set_xlim(0, 10)
    ax.set_ylim(0, 10)
    ax.set_aspect('equal') # Utrzymanie proporcji
    ax.axis('off') # Ukrycie osi

    # --- Pozycje bazowe ---
    x_center = 5
    y_base = 1.0 # Poziom podłoża

    # --- 1. TUŁÓW (Czerwony Prostokąt) ---
    tułów_szerokość = 4.0
    tułów_wysokość = 3.0
    tułów = patches.Rectangle(
        (x_center - tułów_szerokość / 2, y_base + 2.0), # Dolny lewy róg (x, y)
        tułów_szerokość, tułów_wysokość,
        color='#CC0000',
        zorder=2
    )
    ax.add_patch(tułów)

    # --- Pasek (Czarny i Klamra) ---
    pasek = patches.Rectangle((3.0, 4.0), 4.0, 0.5, color='black', zorder=3)
    ax.add_patch(pasek)

    # Klamra (Żółty Kwadrat)
    klamra = patches.Rectangle((4.7, 4.0), 0.6, 0.5, color='#FFD700', zorder=4)
    ax.add_patch(klamra)

    # --- 2. NOGI (Dwa Czerwone Prostokąty) ---
    noga_szerokość = 1.0
    noga_wysokość = 2.0

    # Lewa noga
    noga_lewa = patches.Rectangle(
        (x_center - noga_szerokość - 0.2, y_base),
        noga_szerokość, noga_wysokość,
        color='#CC0000',
        zorder=2
    )
    ax.add_patch(noga_lewa)

    # Prawa noga
    noga_prawa = patches.Rectangle(
        (x_center + 0.2, y_base),
        noga_szerokość, noga_wysokość,
        color='#CC0000',
        zorder=2
    )
    ax.add_patch(noga_prawa)

    # Buty (Czarne, używamy łatek kół, aby zrobić zaokrąglone krawędzie)
    but_lewy = patches.Rectangle((2.8, y_base - 0.5), 1.5, 0.5, color='black', zorder=3)
    but_prawy = patches.Rectangle((5.0, y_base - 0.5), 1.5, 0.5, color='black', zorder=3)
    ax.add_patch(but_lewy)
    ax.add_patch(but_prawy)

    # --- 3. GŁOWA i TWARZ ---
    # Twarz
    twarz = patches.Circle((x_center, 6.5), 1.5, color='#FCDCB0', zorder=5) # Skóra
    ax.add_patch(twarz)

    # Broda (Białe koło pod twarzą)
    broda = patches.Circle((x_center, 5.5), 2.5, color='white', zorder=3)
    ax.add_patch(broda)

    # Oczy
    oko_lewe = patches.Circle((4.2, 6.8), 0.15, color='black', zorder=6)
    oko_prawe = patches.Circle((5.8, 6.8), 0.15, color='black', zorder=6)
    ax.add_patch(oko_lewe)
    ax.add_patch(oko_prawe)

    # Nos
    nos = patches.Circle((x_center, 6.3), 0.2, color='#A00000', zorder=6) # Czerwony nos
    ax.add_patch(nos)

    # --- Czapka ---
    # Czerwony Kapelusz (Trójkąt)
    czapka_korpus = patches.Polygon([[3, 7.5], [7, 7.5], [5, 9.5]], color='#CC0000', zorder=6)
    ax.add_patch(czapka_korpus)

    # Biały otok czapki
    otok = patches.Rectangle((3.0, 7.5), 4.0, 0.5, color='white', zorder=6)
    ax.add_patch(otok)

    # Pompon
    pompon = patches.Circle((5, 9.5), 0.3, color='white', zorder=7)
    ax.add_patch(pompon)

    # --- 4. RĘCE ---
    # Lewe ramię (trzyma worek)
    ramię_lewe = patches.Rectangle((2.0, 5.0), 1.5, 0.7, color='#CC0000', angle=10, zorder=3)
    ax.add_patch(ramię_lewe)

    # Prawe ramię (odstające)
    ramię_prawe = patches.Rectangle((6.5, 5.0), 1.5, 0.7, color='#CC0000', angle=-10, zorder=3)
    ax.add_patch(ramię_prawe)

    # Białe mankiety
    mankiet_lewy = patches.Circle((2.2, 5.0), 0.5, color='white', zorder=4)
    mankiet_prawy = patches.Circle((7.8, 5.0), 0.5, color='white', zorder=4)
    ax.add_patch(mankiet_lewy)
    ax.add_patch(mankiet_prawy)

    # Rękawice (Czarne)
    rękawica_lewa = patches.Circle((1.8, 4.8), 0.4, color='black', zorder=5)
    rękawica_prawa = patches.Circle((8.2, 4.8), 0.4, color='black', zorder=5)
    ax.add_patch(rękawica_lewa)
    ax.add_patch(rękawica_prawa)

    # --- 5. WOREK Z PREZENTAMI ---
    # Używamy elipsy dla kształtu worka
    worek = patches.Ellipse(
        (2.0, 3.0), # Środek worka (x, y)
        2.5, 4.0, # Szerokość i wysokość
        color='#8B4513', # Brązowy kolor
        zorder=1 # Worek jest za Mikołajem
    )
    ax.add_patch(worek)

    # Górna część worka (zmarszczona)
    worek_góra = patches.Polygon(
        [[1.5, 5.0], [2.5, 5.0], [2.2, 5.5], [1.8, 5.5]],
        color='#8B4513',
        zorder=2
    )
    ax.add_patch(worek_góra)

    # Szarfa do zawiązania worka (Żółty prostokąt)
    szarfa = patches.Rectangle((1.5, 5.0), 1.0, 0.2, color='#FFD700', zorder=3)
    ax.add_patch(szarfa)

    plt.title("Mikołaj z workiem (Matplotlib)", fontsize=16)

    # Zwracamy obiekt figury zamiast plt.show()
    return fig

# --- KOD STREAMLIT ---
def main():
    st.title("🎅 Mikołaj w Streamlit")
    st.write("Wygenerowany Mikołaj przy użyciu biblioteki Matplotlib. Worek jest na pierwszym planie (zorder=1), a Mikołaj z tyłu (zorder=2+).")

    # Wywołanie funkcji rysującej
    figura_mikolaja = narysuj_mikolaja_z_workiem()

    # Wyświetlenie figury w aplikacji Streamlit
    st.pyplot(figura_mikolaja)

if __name__ == "__main__":
    main()

